# Generated by Django 4.1.7 on 2025-02-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModerationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mute_words",
                    models.TextField(
                        default="спам, флуд, лох, реклама, лохотрон",
                        help_text="Перераховуйте через кому",
                        verbose_name="Слова для мута",
                    ),
                ),
                (
                    "kick_words",
                    models.TextField(
                        default="тролінг, деструктив, образа",
                        help_text="Перераховуйте через кому",
                        verbose_name="Слова для кіку",
                    ),
                ),
                (
                    "ban_words",
                    models.TextField(
                        default="нацизм, расизм, тероризм, дитяче порно",
                        help_text="Перераховуйте через кому",
                        verbose_name="Слова для бану",
                    ),
                ),
                (
                    "max_mentions",
                    models.IntegerField(default=5, verbose_name="Макс. теги"),
                ),
                (
                    "max_emojis",
                    models.IntegerField(default=10, verbose_name="Макс. емодзі"),
                ),
                (
                    "min_caps_length",
                    models.IntegerField(default=10, verbose_name="Мін. капс"),
                ),
                (
                    "mute_time",
                    models.IntegerField(
                        default=3600, verbose_name="Час мута (секунди)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Налаштування модерації",
                "verbose_name_plural": "Налаштування модерації",
            },
        ),
    ]
