# Generated by Django 5.1.5 on 2025-03-13 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.IntegerField(verbose_name="ІД чату")),
                ("name", models.CharField(max_length=70, verbose_name="Назва чату")),
            ],
            options={
                "verbose_name": "Чати",
                "verbose_name_plural": "Чати",
            },
        ),
        migrations.CreateModel(
            name="ModerationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mute_words",
                    models.TextField(
                        default="спам, флуд, лох, реклама, лохотрон",
                        help_text="Перераховуйте через кому",
                        verbose_name="Слова для мута",
                    ),
                ),
                (
                    "kick_words",
                    models.TextField(
                        default="тролінг, деструктив, образа",
                        help_text="Перераховуйте через кому",
                        verbose_name="Слова для кіку",
                    ),
                ),
                (
                    "ban_words",
                    models.TextField(
                        default="нацизм, расизм, тероризм, дитяче порно",
                        help_text="Перераховуйте через кому",
                        verbose_name="Слова для бану",
                    ),
                ),
                (
                    "max_mentions",
                    models.IntegerField(default=5, verbose_name="Макс. теги"),
                ),
                (
                    "max_emojis",
                    models.IntegerField(default=10, verbose_name="Макс. емодзі"),
                ),
                (
                    "min_caps_length",
                    models.IntegerField(default=10, verbose_name="Мін. капс"),
                ),
                (
                    "mute_time",
                    models.IntegerField(
                        default=3600, verbose_name="Час мута (секунди)"
                    ),
                ),
                (
                    "delete_links",
                    models.BooleanField(
                        default=True, verbose_name="Видаляти повідомлення з посиланнями"
                    ),
                ),
                (
                    "delete_audio",
                    models.BooleanField(
                        default=False, verbose_name="Видаляти аудіозаписи"
                    ),
                ),
                (
                    "delete_video",
                    models.BooleanField(default=False, verbose_name="Видаляти відео"),
                ),
                (
                    "delete_video_notes",
                    models.BooleanField(
                        default=False, verbose_name="Видаляти відеосообщення"
                    ),
                ),
                (
                    "delete_stickers",
                    models.BooleanField(default=False, verbose_name="Видаляти стикери"),
                ),
                (
                    "delete_emojis",
                    models.BooleanField(
                        default=True, verbose_name="Видаляти занадто багато емодзі"
                    ),
                ),
                (
                    "delete_chinese",
                    models.BooleanField(
                        default=False, verbose_name="Видаляти китайські ієрогліфи"
                    ),
                ),
                (
                    "delete_rtl",
                    models.BooleanField(
                        default=False,
                        verbose_name="Видаляти повідомлення з RTL символами",
                    ),
                ),
                (
                    "delete_emails",
                    models.BooleanField(
                        default=True, verbose_name="Видаляти email адреси"
                    ),
                ),
                (
                    "delete_referral_links",
                    models.BooleanField(
                        default=True,
                        verbose_name="Видаляти реферальні посилання Telegram",
                    ),
                ),
                (
                    "emoji_list",
                    models.TextField(
                        default="😀😁😂🤣😃😄😅😆😉😊😋😎😜😝😛🤪🤩🤯🥳😇🥰😍😘",
                        help_text="Перерахуйте емодзі без пробілів",
                        verbose_name="Список емодзі",
                    ),
                ),
            ],
            options={
                "verbose_name": "Налаштування модерації",
                "verbose_name_plural": "Налаштування модерації",
            },
        ),
        migrations.CreateModel(
            name="BannedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("banned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chats_names",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting_bot.chats",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banned User",
                "verbose_name_plural": "Banned Users",
                "ordering": ["-banned_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField()),
                ("message_text", models.TextField()),
                ("action", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "chats_names",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting_bot.chats",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("action_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chats_names",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting_bot.chats",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="setting_bot.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MutedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("end_time", models.DateTimeField()),
                (
                    "chats_names",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting_bot.chats",
                    ),
                ),
            ],
            options={
                "verbose_name": "Muted User",
                "verbose_name_plural": "Muted Users",
                "ordering": ["-end_time"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("is_banned", models.BooleanField(default=False)),
                ("is_muted", models.BooleanField(default=False)),
                ("mute_until", models.DateTimeField(blank=True, null=True)),
                ("banned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chats_names",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting_bot.chats",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMessageCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("message_count", models.IntegerField(default=0)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_message_date", models.DateTimeField(blank=True, null=True)),
                (
                    "chats_names",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting_bot.chats",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_date"],
                "unique_together": {("user_id", "chats_names")},
            },
        ),
    ]
