# Generated by Django 5.1.5 on 2025-03-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionlog",
            name="info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
