# Generated by Django 5.1.5 on 2025-03-15 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting_bot", "0002_actionlog_info"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actionlog",
            options={
                "verbose_name": "Журнал дій",
                "verbose_name_plural": "Журнали дій",
            },
        ),
        migrations.AlterModelOptions(
            name="banneduser",
            options={
                "ordering": ["-banned_at"],
                "verbose_name": "Забанений користувач",
                "verbose_name_plural": "Забанені користувачі",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "verbose_name": "Повідомлення",
                "verbose_name_plural": "Повідомлення",
            },
        ),
        migrations.AlterModelOptions(
            name="muteduser",
            options={
                "ordering": ["-end_time"],
                "verbose_name": "Замучений користувач",
                "verbose_name_plural": "Замучені користувачі",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Користувач",
                "verbose_name_plural": "Користувачі",
            },
        ),
        migrations.AlterModelOptions(
            name="usermessagecount",
            options={
                "ordering": ["-last_message_date"],
                "verbose_name": "Кількість повідомлень користувача",
                "verbose_name_plural": "Кількість повідомлень користувачів",
            },
        ),
        migrations.RemoveField(
            model_name="moderationsettings",
            name="delete_audio",
        ),
        migrations.RemoveField(
            model_name="moderationsettings",
            name="delete_chinese",
        ),
        migrations.RemoveField(
            model_name="moderationsettings",
            name="delete_emails",
        ),
        migrations.RemoveField(
            model_name="moderationsettings",
            name="delete_emojis",
        ),
        migrations.RemoveField(
            model_name="moderationsettings",
            name="delete_links",
        ),
        migrations.RemoveField(
            model_name="moderationsettings",
            name="delete_referral_links",
        ),
        migrations.RemoveField(
            model_name="moderationsettings",
            name="delete_rtl",
        ),
        migrations.RemoveField(
            model_name="moderationsettings",
            name="delete_stickers",
        ),
        migrations.RemoveField(
            model_name="moderationsettings",
            name="delete_video",
        ),
        migrations.RemoveField(
            model_name="moderationsettings",
            name="delete_video_notes",
        ),
        migrations.RemoveField(
            model_name="moderationsettings",
            name="emoji_list",
        ),
        migrations.AddField(
            model_name="moderationsettings",
            name="user",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Модератор",
            ),
            preserve_default=False,
        ),
    ]
