# Generated by Django 5.1.5 on 2025-03-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "setting_bot",
            "0003_alter_actionlog_options_alter_banneduser_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationsettings",
            name="delete_audio",
            field=models.BooleanField(
                default=False, verbose_name="Видаляти аудіозаписи"
            ),
        ),
        migrations.AddField(
            model_name="moderationsettings",
            name="delete_chinese",
            field=models.BooleanField(
                default=False, verbose_name="Видаляти китайські ієрогліфи"
            ),
        ),
        migrations.AddField(
            model_name="moderationsettings",
            name="delete_emails",
            field=models.BooleanField(
                default=True, verbose_name="Видаляти email адреси"
            ),
        ),
        migrations.AddField(
            model_name="moderationsettings",
            name="delete_emojis",
            field=models.BooleanField(
                default=True, verbose_name="Видаляти занадто багато емодзі"
            ),
        ),
        migrations.AddField(
            model_name="moderationsettings",
            name="delete_links",
            field=models.BooleanField(
                default=True, verbose_name="Видаляти повідомлення з посиланнями"
            ),
        ),
        migrations.AddField(
            model_name="moderationsettings",
            name="delete_referral_links",
            field=models.BooleanField(
                default=True, verbose_name="Видаляти реферальні посилання Telegram"
            ),
        ),
        migrations.AddField(
            model_name="moderationsettings",
            name="delete_rtl",
            field=models.BooleanField(
                default=False, verbose_name="Видаляти повідомлення з RTL символами"
            ),
        ),
        migrations.AddField(
            model_name="moderationsettings",
            name="delete_stickers",
            field=models.BooleanField(default=False, verbose_name="Видаляти стикери"),
        ),
        migrations.AddField(
            model_name="moderationsettings",
            name="delete_video",
            field=models.BooleanField(default=False, verbose_name="Видаляти відео"),
        ),
        migrations.AddField(
            model_name="moderationsettings",
            name="delete_video_notes",
            field=models.BooleanField(
                default=False, verbose_name="Видаляти відеоповідомлення"
            ),
        ),
        migrations.AddField(
            model_name="moderationsettings",
            name="emoji_list",
            field=models.TextField(
                default="😀😁😂🤣😃😄😅😆😉😊😋😎😜😝😛🤪🤩🤯🥳😇🥰😍😘",
                help_text="Перерахуйте емодзі без пробілів",
                verbose_name="Список емодзі",
            ),
        ),
    ]
