# Generated by Django 5.1.5 on 2025-03-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting_bot", "0004_moderationsettings_delete_audio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banneduser",
            name="banned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="muteduser",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
