# Generated by Django 5.1.5 on 2025-03-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting_bot", "0005_alter_banneduser_banned_at_alter_muteduser_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="banneduser",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="muteduser",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
