# Generated by Django 5.1.5 on 2025-03-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting_bot", "0006_banneduser_status_muteduser_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
