# Generated by Django 5.1.5 on 2025-03-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting_bot", "0007_user_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="muteduser",
            name="chats_names",
        ),
        migrations.AlterUniqueTogether(
            name="usermessagecount",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usermessagecount",
            name="chats_names",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-last_message_date"],
                "verbose_name": "Користувач",
                "verbose_name_plural": "Користувачі",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="last_message_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="message_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="mute_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("user_id", "chats_names")},
        ),
        migrations.DeleteModel(
            name="BannedUser",
        ),
        migrations.DeleteModel(
            name="MutedUser",
        ),
        migrations.DeleteModel(
            name="UserMessageCount",
        ),
    ]
