# Generated by Django 5.1.5 on 2025-03-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting_bot", "0008_remove_muteduser_chats_names_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="moderationsettings",
            name="mute_time",
            field=models.IntegerField(default=3600, verbose_name="Час мута (хвилини)"),
        ),
    ]
