# Generated by Django 5.1.5 on 2025-03-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting_bot", "0009_alter_actionlog_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionlog",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
