# Generated by Django 5.1.5 on 2025-04-07 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting_bot", "0010_actionlog_first_name_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionlog",
            name="chats_names",
        ),
        migrations.AddField(
            model_name="actionlog",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="setting_bot.chats",
            ),
        ),
        migrations.CreateModel(
            name="ChatMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_banned", models.BooleanField(default=False)),
                ("is_muted", models.BooleanField(default=False)),
                ("mute_count", models.IntegerField(default=0)),
                ("mute_until", models.DateTimeField(blank=True, null=True)),
                ("banned_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("message_count", models.IntegerField(default=0)),
                ("last_message_date", models.DateTimeField(blank=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting_bot.chats",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участь користувача у чаті",
                "verbose_name_plural": "Участі користувачів у чатах",
                "ordering": ["-last_message_date"],
            },
        ),
        migrations.AddField(
            model_name="actionlog",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="setting_bot.chatmembership",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="setting_bot.chatmembership",
            ),
        ),
        migrations.CreateModel(
            name="ChatUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "chats",
                    models.ManyToManyField(
                        related_name="users",
                        through="setting_bot.ChatMembership",
                        to="setting_bot.chats",
                    ),
                ),
            ],
            options={
                "verbose_name": "Користувач",
                "verbose_name_plural": "Користувачі",
            },
        ),
        migrations.AddField(
            model_name="chatmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="setting_bot.chatuser"
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AlterUniqueTogether(
            name="chatmembership",
            unique_together={("user", "chat")},
        ),
    ]
