# Generated by Django 5.1.5 on 2025-04-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting_bot", "0011_remove_actionlog_chats_names_actionlog_chat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationsettings",
            name="morphology",
            field=models.BooleanField(default=True, verbose_name="Морфологія"),
        ),
        migrations.AddField(
            model_name="moderationsettings",
            name="morphology_worlds_lang_ru",
            field=models.TextField(
                default="порно",
                help_text="Перераховуйте через кому",
                verbose_name="Слова для морфології_ru",
            ),
        ),
        migrations.AddField(
            model_name="moderationsettings",
            name="morphology_worlds_lang_uk",
            field=models.TextField(
                default="порно",
                help_text="Перераховуйте через кому",
                verbose_name="Слова для морфології_УК",
            ),
        ),
    ]
